### ISSUE TITLE
VMs are automatically going into stopped state

### ISSUE THREAD

**Issue by reddyskp** [fortinet/fortigate-autoscale-gcp#27]
Hi All,

VM's are automatically going into stopped state after executing the script vms are running fine. Within 2 minutes they are going into stopped state. Please help me how to resolve this issue

![image](https://user-images.githubusercontent.com/90032329/135799488-d4e2cf75-3334-4f5e-a0c9-6fb86b7fab66.png)

**Comment by reddyskp** [comment]
Instance logs shows,
compute.googleapis.com
**compute.instances.guestTerminate
…s/fortigateautoscale-instance-cbrbr-7cvs
system@google.com
Instance terminated by guest OS shutdown.**

**Comment by Joel-Cripps** [comment]
My first guess is that something went wrong with the boot-strap config. Can you share the results of : `diag debug cloudinit show` as well as the bootstrap config?

You may need to disable your health probe to disable deletion.

**Comment by Joel-Cripps** [comment]
I'm going to close this up. If you are still having issues feel free  to open a new issue and reference this.
